name: Deploy

on:
  push:
    branches:
      - dev

jobs:
  deploy_lambda:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: 'Configure AWS Credentials'
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
      - name: 'npm install'
        env:
          CI: true
        run: |
          npm ci
      # TODO: add testing
      - name: 'deploy'
        run: |
          npm run ncc build src/app.ts
          zip -j deploy.zip ./dist/*
          aws lambda update-function-code --function-name=buckaroo -zip-file=fileb://deploy.zip
