name: Deploy

on:
  push:
    branches:
      - dev
      

jobs:
  deploy_lambda:
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v2
      - uses: action/setup-node@v2
        with:
          node-version: '12'
      - name: 'npm install'
        env:
          CI: true
        run: |
          npm ci
